# Generated by Django 4.2.4 on 2023-08-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0003_alter_video_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
