# Generated by Django 4.2.4 on 2023-08-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0004_alter_video_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.TextField(),
        ),
    ]
