# Generated by Django 4.2.4 on 2023-08-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0005_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(),
        ),
    ]
