# Generated by Django 4.2.4 on 2023-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_userown_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userown',
            name='images',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
