# Generated by Django 4.2.4 on 2023-08-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_userown_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userown',
            name='images',
            field=models.IntegerField(default=0),
        ),
    ]
