# Generated by Django 4.2.4 on 2023-08-27 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_images', '0004_alter_image_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 17, 40, 49, 532814)),
        ),
    ]
